export const domain = "https://embed.invi.one"
export const mainDomain = "https://invi.one"
export const discohook = "https://discohook.org"
export const discohookSource = "https://github.com/discohook/site"
export const source = "https://github.com/Siris01/invi-embed-builder"
